name: Gitee repos mirror

on: [push]

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
    - name: Hub Mirror Action.
      uses: Yikun/hub-mirror-action@v0.07
      with:
        src: wisecrm/dev-docs
        dst: wisecrm/dev-docs
        dst_key: ${{ secrets.GITEE_PRIVATEKEY }}
        dst_token: ${{ secrets.GITEE_TOKEN }}
        account_type: user
        white_list: "dev-docs"
